### PR TITLE
20170624 transaltions

### PR DESCRIPTION
**Pull request by dark-eye**
- Updated the main .pot translation file to match the code

### CODE REVIEW

**Comment by Flohack74** [comment]
I will merge this into Weblate :)

**Comment by dark-eye** [comment]
I've reverted the  hebrew translation  to prevent possible issues with the site :)

**Comment by Flohack74** [comment]
Nono this is not what I meant! I mean, finish it here, then I activate it in Weblate. We should not just change things on BOTH ends :) go push it fully, what you got here, then I merge, then I activate the weblate project

**Comment by dark-eye** [comment]
I reverted the Hebrew translation as I created it manually (using msgmerge tool) from the template and  was afraid it won't match the what Weblates is doing to generate the translation, and might cause issues...

I can do the translation in weblates it much more  exciting :yum:

**Comment by Flohack74** [comment]
Ook kwell then lets go =)

**Pull request closed without merging**
