### PR TITLE
implemented theme live switching

### PR DESCRIPTION
**Pull request by mymike00**
without the need to restart the app

### CODE REVIEW

**Comment by mymike00** [comment]
here the [.click](https://my.owndrive.com/index.php/s/y29PTPD2qpDbN65) that merges PRs #105 #106 and #108 (this one). I incremented the version number in the `.click` to show changes after installing the app as it's a core app

**Comment by dark-eye** [comment]
@mymike00  there's seems that thes change causes a problem with the bottom edge, if the bottom edge is opened with one theme it`s will fail to be open with the new theme.
(This is probably  some kind of caching issue)

**Comment by mymike00** [comment]
Oh, weird. I'll look into it

**Comment by mymike00** [comment]
I saw that if you open the bottomedge, then you change theme when you try to open again the bottomedge it's empty: now, if you open it again the bottomedge will work. you can do it by either drag it up for a bit and then drag it down (so you are able to open the bottom edge twice) or if you open completely the bottom edge and you have a blank (or grey) screen just do the drag as to open the bottomedge even if you don't see anything.
also the bottomedge is loaded as soon as possible so when you change theme I think you should `destroy()` the bottomedge but I can't do it yet

**Review by dark-eye — CHANGES_REQUESTED** [review]
Just to document the  current state of this PR...
This currently  create a regression with the bottom edge  displaying  a blank page when changing the theme (this is  most likely a bottom edge issue) it  can be  worked around if you can collapse it but  after a full commit  of the  bottom edge you`ll have to restart the clock app.

**Comment by mymike00** [comment]
> but after a full commit of the bottom edge you`ll have to restart the clock app.

do, you don't have to do it. just drag normally from the bottom to open the bottomedge even it's already opened and while dragging it, collapse it so you can still use the app

**Comment by mymike00** [comment]
maybe I fix it, not sure if it's the right way tbh... I'm just worried because I get strange logs that should be there I think.
I added a function inside `app/MainPage.qml` that set the source of the Loader `bottomEdgeLoader` (it doeas same thing as what done in Component.conCompleted in that Loader)
in `ubuntu-clock-app.qml` in the MainView I added `theme.onNameChanged: mainPage.reloadBottomEdge()` that calls the previous function when the theme is changed

**Comment by mymike00** [comment]
check the changes in the [live_theme_test](https://github.com/mymike00/clock-app/tree/live_theme_test) branch. it has some issue (the weird logs), that's why I didn't pushed it here...

**Comment by mymike00** [comment]
the PR is ready for merge imho. @dark-eye can you have a look, please?

**Comment by dark-eye** [comment]
Oh no i`m sorry @mymike00 i was   quite busy last month  and got a little disoriented i`ll have a look  at it...

**Comment by dark-eye** [comment]
@mymike00 Seems to be working great i`ll test it for a few  days just to make sure i don't identify any regression as  the code change seems a little 'race conditionay' :)  and if all is good i`ll merge it.

**Review by dark-eye — APPROVED** [review]

**Comment by mymike00** [comment]
> the code change seems a little 'race conditionay' :) 
no, it shouldn't ... the timer is just to wait for the listitem to get collapsed, otherwise if I change theme before it, it'll stuck half-opened...

**Pull request merged**
