### PR TITLE
WIP : Clock app #47 :  reordering the alarm list by the closet  alarm and past  alarms at the bottom 

### PR DESCRIPTION
**Pull request by dark-eye**
**This PR Might not be worth the added complexity it add to the code just to reorder the alarm list a little**
I created it anyway so the community can decide about it...

Fix for Clock app #47 : reordering the alarm list by the closet alarm and past alarms at the bottom

Also in this PR :
- Fixed an issue that caused alarms to sometimes miss-match the  enabled switch from their actual enabled state. 
- Added user metrics of alarms created today
- Also made the alarm adding/removing/displacement animation a little more prominent.

### CODE REVIEW

**Comment by Flohack74** [comment]
@sverzegnassi maybe you also take a look here? Would be glad if in the future this will be primarily handled in the App team ;)

**Comment by sverzegnassi** [comment]
Code looks good to me, I just have some concern on the sorting itself (see screenshot).

First two entries in the list have been previously both enabled, in order to schedule an alarm for tomorrow. The first entry has been then disabled.

I suspect the current `lessThan()` function takes in account the `YYYY-MM-DD hh:mm:ss` date of when the the alarm for an entry is expected (or was expected) to ring.

It might be preferable to take in account just the `hh:mm` as reported in the UI, above the alarm label (i.e. "Alarm" or "Sveglia" in the screenshot), in order to consistently sort alarm, independently from the status (enabled or disable) or the settings for repetition.

screenshot20171208_132449504

**Comment by dark-eye** [comment]
Hey @sverzegnassi 

Sorry for the late reply, 
I was about to explain the logic behind the sorting but then i understood that if it needs explaining then it probably not the best solution.

It think the issue is that we have past and future alarms in the same list this pull request was meant to move the past alarms from accumulating at the top of the list but it obliviously created a UX issue as the list is a little confusing.

I think to move on i can change the sorting to your solution for now (hh:mm), but will keep the issue open as  i do think that sorting it based on the closet next alarm is much more user friendly as it let the user see the alarm by the order they will occur, though that might require some redesign to the UI in order to make it clear for the user what he is actually looking at :)

**Comment by Flohack74** [comment]
Could we split the list in 2 parts "Active alarms" and "Inactive"? Then all this complexity could be reduced

**Comment by dark-eye** [comment]
@Flohack74 yes  thats  was one of the thoughts i had on the redesign.
But i think it should be "Future Alarms" and "Past alarms" as inactive/active might confuse the user with the enabled/disabled, In any case to that i need to find a way to add property to the alarm model... investigating...

**Comment by sverzegnassi** [comment]
Had a check into the [official UX specs for clock-app](https://nc.ubports.com/apps/files/?dir=/Canonical%20Design%20Documents%20%5BPUBLIC%5D&fileid=20992#pdfviewer) - page 6. They expected alarms to be sorted by hh:mm, like it happens on Android and iOS.

I might be biased here, and I don't have any data, but my guess is that generally people search alarms for hh:mm first, then they look for the week days and alarm status.
That seems confirmed by the adoption of this solution on the main platform.

About listing enabled alarms first, that's up to you @dark-eye . If you could provide it, it would be appreciated by many :)
Combined with the 'hh:mm' sorting, it could indeed help reducing the cognitive load for the alarms management.

**Comment by dark-eye** [comment]
@sverzegnassi Right, Lets move to HH:MM sorting. 
(if there will be complaints we can switch back or provide a configurable selection option :) )

I think I've found how i can add data to the model i`ll try it once i`ll have time.

**Comment by Flohack74** [comment]
@dark-eye if you have time, plz check the conflicts so that we can proceed here.

**Comment by Flohack74** [comment]
Whats the state here @dark-eye

**Comment by dark-eye** [comment]
Changing  the ordering behavior is a little problematic as it expose an issue  that already  exists ( #72 ) those creating a ( perceived ) regression , I've tried to find a good solution for it but it seems to be a QT problem (any workarounds i was able to think of did more harm to the user experience then good ) how ever i didn't tested it under 5.9 so it might be fixed i`ll give it a try when i have some free time.

**Comment by Flohack74** [comment]
Nice thx, and the sorting by hh:mm is implemented yet?

**Comment by dark-eye** [comment]
@Flohack74 It is now, also since it disable the enable/disable resorting it should avoid the issue that was mentioned at #72

**Pull request merged**
